name: http_pagination
description: Http headers pagination. Parses a link header (web links) into useful models
version: 0.2.2
repository: https://github.com/Frezyx/http_pagination

environment:
  sdk: '>=2.18.6 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
